version: 2

models:
  - name: get_stop_search

    description: UK Stop and Search Data

    config:
      materialized: table
      tags: ['python']
  - name: get_workforce_by_ethnicity

    description: Police Workforce by Ethnicity Data

    config:
      materialized: table
      tags: ['python']

  - name: get_police_forces_data

    description: Police Workforces Extra Data

    config:
      materialized: table
      tags: ['python']